### ISSUE TITLE
wayland touchscreen support

### ISSUE THREAD

**Issue by dexterdy** [sunwxg/gnome-shell-extension-floatingDock#11]
Whenever I try to use my touchscreen with this application, the problem occurs. The dock registers the touch as hovering my mouse over the application instead of clicking. I am unable to click any of the applications. I am able to click the application menu and the three dots for some reason. It would also be nice if a long press would be registered as a right click.

I am on fedora 34

**Comment by sunwxg** [comment]
I don't have touchscreen hardware, so I didn't test in on touchscreen before.
I'll try to improve it.

**Comment by sunwxg** [comment]
Try to use the latest code on github to test the clicking on touch screen.
Thank you!

**Comment by dexterdy** [comment]
thanks for your reply. i will try this

**Comment by dexterdy** [comment]
it works now! thank you
