### ISSUE TITLE
touchscreen wayland | right-click menu and multiple windows of the same program

### ISSUE THREAD

**Issue by dexterdy** [sunwxg/gnome-shell-extension-floatingDock#19]
Hello there,

Some time ago I created an issue because none of the icons reacted to touch input. This was then fixed quite quickly :1st_place_medal: . I am now creating an issue for additional touchscreen support on wayland. You see, there is no way for a user to open de right-click menu using only the touchscreen. Similarly, when you have multiple windows of the same program open, it is impossible to select a window. These are issues when using a convertible laptop in tablet mode. 

Some more clarification for the second issue: When you have multiple windows of the same program open, you can click the icon and it opens the menu where you can select which window you would want to go to. When you then click a window, it does show that it gets selected (see image), but when you release, the menu disappears and nothing happens:

![Screenshot from 2021-08-12 14-49-42](https://user-images.githubusercontent.com/28401039/129199572-d8786ea1-4800-4481-a6a7-6db2738c418e.png)

**Comment by sunwxg** [comment]
Two finger tap equals right click. This works on my apple Magic trackpad.
For the second issue, I will improve it.
