### ISSUE TITLE
不显示正常的图标，不知哪问题

### ISSUE THREAD

**Issue by oreak** [sunwxg/gnome-shell-extension-floatingDock#27]
如下两个不正常的就是 左边  微信 和  wiznote , 左边是正常的 desktop,   右边不正常的是 运行起来后的 

![gnome_docker](https://user-images.githubusercontent.com/6316576/156162094-cee848ae-4b0e-4e10-99df-06f387feaed2.png)
![gnome_docker_2](https://user-images.githubusercontent.com/6316576/156162104-eb63d888-3973-413d-b3f7-ed9f811b789b.png)

**Comment by sunwxg** [comment]
微信和wiznote是wine app还是flatpak app？
在gnome-shell的dock里也是这么显示的吗？如果是的话，那可能是gnome-shell或app的问题.

**Comment by oreak** [comment]
> 微信和wiznote是wine app还是flatpak app？ 在gnome-shell的dock里也是这么显示的吗？如果是的话，那可能是gnome-shell或app的问题.

不是wine app也不是flatpak app ， 是 AppImage解压出来的， 问题是 那个运行起来的小马那个图标 也是这种格式运行起来的，它就是正常图标，我只是不知道这是什么原因，肯定不是你这个dock 问题， 因为gnome-shell 的dock 就是这样显示的。

**Comment by sunwxg** [comment]
那就是APP的问题了，图标放的位置不符合发行版的要求，gnome-shell找不到造成的。

**Comment by oreak** [comment]
> 那就是APP的问题了，图标放的位置不符合发行版的要求，gnome-shell找不到造成的。

好的我再看看，现在知道的是跟这种图标有关的 有 .desktop ,  .DirIcon 文件，不清楚还跟什么有关，如果你以后知道的话，记得和我说说，谢谢了

**Comment by sunwxg** [comment]
通常图标的文件是.svg, 一般放在/usr/share/icons/hicolor/scalable/apps/这个目录下，发行版不同，这个目录可能有所不同。
