### ISSUE TITLE
Unable to run on Ubunut 20.04

### ISSUE THREAD

**Issue by omerasif57** [sunwxg/gnome-shell-extension-floatingDock#5]
I install using `make install` instructions.
Restarted my computer
And No sign of visuals 
Check gnome extensions app/tweaks comes by default. 

Am I missing something here?

**Comment by sunwxg** [comment]
Was the extension enabled?
When the extension is enabled first time, the button is on the top-left of screen.

**Comment by sunwxg** [comment]
I recommend you go to web extensions.gnome.org to install this extension, it can make you use right version.

**Comment by omerasif57** [comment]
> I recommend you go to web extensions.gnome.org to install this extension, it can make you use right version.

Alright. I will try.

> Was the extension enabled?
> When the extension is enabled first time, the button is on the top-left of screen.

I checked into gnome-extenstions app, also in tweaks app which comes by default in ubuntu 20. There was no mention of floating dock there.

**Comment by omerasif57** [comment]
My gnome-shell was at 3.36. Working now. Thanks. 
By the way, It stays sticky over the Apps. Might be rad if hide when inactive. Still, It's Perfect!
