### ISSUE TITLE
On the 2nd workspace, clicking on the icon of an app on the 1st workspace doesn't open

### ISSUE THREAD

**Issue by chdslv** [sunwxg/gnome-shell-extension-floatingDock#6]
On the 2nd workspace, clicking on the icon on the dock, it won't go to the first work space to show the app, but a new instance of the app would open on the 2nd work space. There's no connection between the open apps in different work spaces and the floating dock, not as in Dash or D2D. 

![open_apps_not_shown](https://user-images.githubusercontent.com/28350701/114163892-f9968700-992a-11eb-971e-9451c889db10.jpg)
There are few apps open in other work spaces, but not shown, no dots.

**Comment by sunwxg** [comment]
Yes, the dot only indicates the opened app in current workspace, it's different with Dash

**Comment by chdslv** [comment]
Yes, but is there a way to implement that? If that's implemented, your dock would be super. It is quite good for one desktop, though. It is actually lovely!

**Comment by sunwxg** [comment]
I think it can be implemented. Add it in the future.

**Comment by chdslv** [comment]
Excellent!
If you can, add the Show Applications icon too. :)

**Comment by chdslv** [comment]
Thank you!
That was excellent!
