### ISSUE TITLE
Is it possible to move the dot down?

### ISSUE THREAD

**Issue by i5o** [sunwxg/gnome-shell-extension-floatingDock#7]
Hello there :)

I was wondering if there is any way to move the dot below the icon 
![image](https://user-images.githubusercontent.com/2650479/114425872-dd475400-9b8f-11eb-91b7-870ebacba7d9.png)

I know this is possible with "dash" but I would like to have an icon below, it looks cool ;P

anyway, great job, I love this!

**Comment by i5o** [comment]
Another question, is it possible to make the cursor a "hand" or whatever it's called when hovering the icon?
thanks :B

**Comment by sunwxg** [comment]
It's possible that the dot is on bottom, add an option later.
`make the cursor a "hand"` that means changing the mouse point type, I think that is a little complicated, I don't consider it now.

**Comment by i5o** [comment]
thank you 3;
